plugins {
    id 'com.android.application'
}

android {
    namespace 'com.localmod.batterydisplay'
    compileSdk 33

    defaultConfig {
        applicationId "com.localmod.batterydisplay"
        minSdk 27
        targetSdk 33
        versionCode 1
        versionName "0.1"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    // 仅编译期需要，运行时由 LSPosed 框架提供，不会打进最终 APK
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly 'de.robv.android.xposed:api:82:sources'
}
